# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/assetpulse
spring.datasource.username=assetpulse_user
spring.datasource.password=assetpulse_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# App
server.port=8080
spring.application.name=assetpulse-backend

# OpenAPI docs
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

# Java 21 Virtual Threads ? replaces the default Tomcat thread pool
spring.threads.virtual.enabled=true